export const GET_FAVORITES = 'GET_FAVORITES';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_FAIL = 'ADD_FAVORITE_FAIL';

export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const REMOVE_FAVORITE_SUCCESS = 'REMOVE_FAVORITE_SUCCESS';
export const REMOVE_FAVORITE_FAIL = 'REMOVE_FAVORITE_FAIL';